extern crate raw_handle_derive;

pub use sys::load_with;

pub(crate) mod macros;
pub mod buffer_objects;

/**
 * INTERNAL
 * Only used to facilitate import paths
 */
mod gl {
    pub use crate::sys::types::*;
    pub use crate::sys::*;
}


/**
 * Module containing raw OpenGL bindings as generated by gl_generator
 */
pub mod sys {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

    pub trait RawHandle<T> {
        /// # Safety
        /// The raw types should not be handled manually, unless not possible
        unsafe fn raw_handle(&self) -> T;

        /// # Safety
        /// The raw types should not be handled manually, unless not possible
        unsafe fn from_raw(value: T) -> Self;
    }
}
